mplayer-cvs, ffmpeg-cvs, vlc-svn sync
git-svn-id: https://4nykey.googlecode.com/svn@44 1790357a-5c2d-0410-b753-991ad51f65a7

diff --git a/media-video/ffmpeg-cvs/files/FFMpeg-20051205-dirac-0.5.x.patch b/media-video/ffmpeg-cvs/files/FFMpeg-20051205-dirac-0.5.x.patch
--- a/media-video/ffmpeg-cvs/files/FFMpeg-20051205-dirac-0.5.x.patch
+++ b/media-video/ffmpeg-cvs/files/FFMpeg-20051205-dirac-0.5.x.patch
@@ -1,188 +1,89 @@
-Index: Makefile
-===================================================================
-RCS file: /cvsroot/mplayer/main/Makefile,v
-retrieving revision 1.333
-diff -u -r1.333 Makefile
---- Makefile	16 Nov 2005 10:38:23 -0000	1.333
-+++ Makefile	16 Dec 2005 11:17:41 -0000
-@@ -106,6 +106,7 @@
-              $(JPEG_LIB) \
-              $(ALSA_LIB) \
-              $(XMMS_LIB) \
-+             $(DIRAC_LIB) \
-              $(X264_LIB) \
-              $(MUSEPACK_LIB) \
-              $(SPEEX_LIB) \
-Index: configure
-===================================================================
-RCS file: /cvsroot/mplayer/main/configure,v
-retrieving revision 1.1111
-diff -u -r1.1111 configure
---- configure	14 Dec 2005 21:52:40 -0000	1.1111
-+++ configure	16 Dec 2005 11:17:55 -0000
-@@ -264,6 +264,7 @@
-   --disable-amr_nb       disable amr narrowband, floating point [autodetect]
-   --disable-amr_nb-fixed disable amr narrowband, fixed point [autodetect]
-   --disable-amr_wb       disable amr wideband, floating point [autodetect]
-+  --enable-dirac         build with Dirac support [autodetect]
-   --disable-codec=CODEC  disable specified codec
-   --enable-codec=CODEC   dnable specified codec
-   
-@@ -1571,6 +1572,7 @@
- _ftp=yes
- _musepack=auto
- _vstream=auto
-+_dirac=auto
- _pthreads=yes
- for ac_option do
-   case "$ac_option" in
-@@ -1868,6 +1870,9 @@
-   --enable-sortsub) _sortsub=yes ;;
-   --disable-sortsub) _sortsub=no ;;
+diff -ruN --exclude=CVS ffmpeg-cvs/configure ffmpeg-cvs-dirac/configure
+--- ffmpeg-cvs/configure	2005-11-29 21:12:30.000000000 +0000
++++ ffmpeg-cvs-dirac/configure	2005-12-01 15:51:21.000000000 +0000
+@@ -42,6 +42,7 @@
+ echo "                           and libraw1394 [default=no]"
+ echo "  --enable-gpl             allow use of GPL code, the resulting libav*"
+ echo "                           and ffmpeg will be under GPL [default=no]"
++echo "  --enable-dirac           enable dirac codec support via libdirac_encoder/decoder [default=no]"
+ echo ""
+ echo "Advanced options (experts only):"
+ echo "  --source-path=PATH       path to source code [$source_path]"
+@@ -207,6 +208,7 @@
+ dostrip="yes"
+ installstrip="-s"
+ extralibs="-lm"
++extraincs=""
+ simpleidct="yes"
+ bigendian="no"
+ inttypes="yes"
+@@ -236,6 +238,7 @@
+ amr_if2="no"
+ sunmlib="no"
+ pthreads="no"
++dirac="no"
+ gpl="no"
+ memalignhack="no"
+ muxers="yes"
+@@ -560,6 +563,11 @@
+   ;;
+   --enable-pthreads) pthreads="yes"
+   ;;
++  --enable-dirac) dirac="yes"
++    extraincs="$extraincs `pkg-config --cflags dirac`"
++    extralibs="$extralibs `pkg-config --libs dirac` -lstdc++"
++    pkg_requires="$pkg_requires dirac"
++  ;;
+   --enable-gpl) gpl="yes"
+   ;;
+   --enable-memalign-hack) memalignhack="yes"
+@@ -586,6 +594,14 @@
+   esac
+ done
  
-+  --enable-dirac) _dirac=yes ;;
-+  --disable-dirac) _dirac=no ;;
++if test "$dirac" = "yes" ; then
++	`pkg-config --cflags dirac` `pkg-config --libs dirac` -lstdc++ > /dev/null 2>&1
++    if test $? = 0 ; then
++        echo "Could not find dirac on system."
++        dirac="no"
++    fi
++fi
 +
-   --charset=*)
-     _charset=`echo $ac_option | cut -d '=' -f 2`
-     ;;
-@@ -7009,6 +7014,53 @@
+ if test "$theora" = "yes" ; then
+     if test "$libogg" = "no"; then
+         echo "libogg must be enabled to enable Theora."
+@@ -1246,6 +1262,7 @@
+ echo "shared pp        $shared_pp"
+ echo "video hooking    $vhook"
+ echo "SDL support      $sdl"
++echo "dirac enabled    $dirac"
+ if test $sdl_too_old = "yes"; then
+ echo "-> Your SDL version is too old - please upgrade to have FFplay/SDL support."
  fi
- echores "$_lircc"
+@@ -1452,6 +1469,7 @@
+   echo "SPPVERSION=0.0.1" >> config.mak 
+ fi
+ echo "EXTRALIBS=$extralibs" >> config.mak
++echo "EXTRAINCS=$extraincs" >> config.mak
+ version=`grep '#define FFMPEG_VERSION ' "$source_path/libavcodec/avcodec.h" |
+  cut -d '"' -f 2`
+ echo "VERSION=$version" >>config.mak
+@@ -1680,6 +1698,11 @@
+   echo "CONFIG_FFPLAY=yes" >> config.mak
+ fi
  
-+echocheck "Dirac support (version 5.2!)"
-+if test "$_dirac" = auto ; then
-+  _dirac=no
-+  cat > $TMPC << EOF
-+#include <libdirac_decoder/dirac_parser.h>
-+#include <string.h>
-+int main(void) 
-+{ 
-+  /* dirac is in flux, make sure that all interface routines and 
-+   * datatypes exist and work the way we expect it, so we don't break
-+   * mplayer */
-+  dirac_decoder_t *decoder;
-+  unsigned char *yuv[3];
-+  char buffer[1024];
-+  dirac_chroma_t chroma;
-+  dirac_frame_type_t frame;
-+  dirac_seqparams_t seq_params;
-+  dirac_frameparams_t frame_params;
-+  dirac_framebuf_t frame_buf;
-+  DecoderState state;
-+
-+  decoder = dirac_decoder_init(0);
-+
-+  /* we don't want to execute this kind of nonsense; just for making sure
-+   * that compilation works... */
-+  memset(&buffer, 0, sizeof(buffer));
-+  dirac_buffer (decoder, buffer, buffer + sizeof(buffer));
-+  state = dirac_parse (decoder);
-+  dirac_set_buf (decoder, yuv, NULL);
-+  dirac_skip(decoder, 1);
-+  dirac_decoder_close(decoder);
-+  return 0;
-+}
-+EOF
-+  cc_check `pkg-config --cflags dirac` `pkg-config --libs dirac` -lstdc++ && _dirac=yes
++if test "$dirac" = "yes" ; then
++  echo "#define CONFIG_DIRAC 1" >> $TMPH
++  echo "CONFIG_DIRAC=yes" >> config.mak
 +fi
-+if test "$_dirac" = yes ; then
-+  _def_dirac='#define HAVE_DIRAC 1'
-+  _codecmodules="libdirac $_codecmodules"
-+  _inc_dirac=`pkg-config --cflags dirac`
-+  _ld_dirac="`pkg-config --libs dirac` -lstdc++"
-+else
-+  _def_dirac='#undef HAVE_DIRAC'
-+  _nocodecmodules="libdirac $_nocodecmodules"
-+fi
-+echores "$_dirac"
 +
- #############################################################################
- echo "Creating config.mak"
- cat > config.mak << EOF
-@@ -7200,6 +7252,9 @@
- AMR_NB=$_amr_nb
- AMR_NB_FIXED=$_amr_nb_fixed
- AMR_WB=$_amr_wb
-+CONFIG_DIRAC = $_dirac
-+DIRAC_LIB = $_ld_dirac
-+DIRAC_INC = $_inc_dirac
- `echo $_libavcodecs | tr '[a-z] ' '[A-Z]\n' | sed 's/^/CONFIG_/;s/$/=yes/'`
- CONFIG_GPL=yes
- 
-@@ -7772,6 +7827,9 @@
- /* enable Matroska support */
- $_def_matroska
- 
-+/* enable Dirac support */
-+$_def_dirac
-+
- /* enable FAAD (AAC) support */
- $_def_faad
- $_def_faad_internal
-Index: etc/codecs.conf
-===================================================================
-RCS file: /cvsroot/mplayer/main/etc/codecs.conf,v
-retrieving revision 1.442
-diff -u -r1.442 codecs.conf
---- etc/codecs.conf	9 Dec 2005 16:52:44 -0000	1.442
-+++ etc/codecs.conf	16 Dec 2005 11:18:02 -0000
-@@ -244,6 +244,16 @@
-   dll libtheora
-   out YV12
- 
-+videocodec dirac
-+  info "Dirac (libdirac_decoder)"
-+  comment "work in progress"
-+  status working
-+  fourcc drac
-+  format 0x20000001
-+  driver ffmpeg
-+  dll "dirac"
-+  out IYUV,422P
-+
- ; prefer native codecs over win32?
- ; the win32 codecs probably are (better) optimized and support direct
- ; rendering, so this may be not the best idea...
-? libavcodec/dirac.c
-? libavformat/drc.c
-Index: libavcodec/Makefile
-===================================================================
-RCS file: /cvsroot/ffmpeg/ffmpeg/libavcodec/Makefile,v
-retrieving revision 1.215
-diff -u -r1.215 Makefile
---- libavcodec/Makefile	10 Dec 2005 17:14:23 -0000	1.215
-+++ libavcodec/Makefile	16 Dec 2005 11:18:10 -0000
-@@ -7,7 +7,7 @@
- VPATH=$(SRC_PATH)/libavcodec
- 
- # NOTE: -I.. is needed to include config.h
--CFLAGS=$(OPTFLAGS) -DHAVE_AV_CONFIG_H -I.. -I$(SRC_PATH)/libavutil -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE $(AMR_CFLAGS)
-+CFLAGS=$(OPTFLAGS) -DHAVE_AV_CONFIG_H -I.. -I$(SRC_PATH)/libavutil -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE $(AMR_CFLAGS) $(EXTRAINCS)
- 
- OBJS= bitstream.o utils.o mem.o allcodecs.o \
-       mpegvideo.o jrevdct.o jfdctfst.o jfdctint.o\
-@@ -304,6 +304,12 @@
- endif
- endif
- 
-+ifeq ($(CONFIG_DIRAC),yes)
-+OBJS += dirac.o
-+EXTRALIBS += $(DIRAC_LIB)
-+CFLAGS += $(DIRAC_INC)
-+endif
-+
- ifeq ($(CONFIG_LIBGSM),yes)
- OBJS += libgsm.o
- endif
-Index: libavcodec/allcodecs.c
-===================================================================
-RCS file: /cvsroot/ffmpeg/ffmpeg/libavcodec/allcodecs.c,v
-retrieving revision 1.117
-diff -u -r1.117 allcodecs.c
---- libavcodec/allcodecs.c	9 Dec 2005 16:08:18 -0000	1.117
-+++ libavcodec/allcodecs.c	16 Dec 2005 11:18:10 -0000
-@@ -525,6 +525,14 @@
+ if test "$gpl" = "yes" ; then
+   echo "#define CONFIG_GPL 1" >> $TMPH
+   echo "CONFIG_GPL=yes" >> config.mak
+diff -ruN --exclude=CVS ffmpeg-cvs/libavcodec/allcodecs.c ffmpeg-cvs-dirac/libavcodec/allcodecs.c
+--- ffmpeg-cvs/libavcodec/allcodecs.c	2005-11-30 01:40:50.000000000 +0000
++++ ffmpeg-cvs-dirac/libavcodec/allcodecs.c	2005-12-01 11:58:20.000000000 +0000
+@@ -522,6 +522,14 @@
      register_avcodec(&bmp_decoder);
  #endif
  
@@ -197,13 +98,9 @@ diff -u -r1.117 allcodecs.c
      /* pcm codecs */
  #if defined (CONFIG_ENCODERS) && defined (CONFIG_DECODERS)
      #define PCM_CODEC(id, name) \
-Index: libavcodec/avcodec.h
-===================================================================
-RCS file: /cvsroot/ffmpeg/ffmpeg/libavcodec/avcodec.h,v
-retrieving revision 1.430
-diff -u -r1.430 avcodec.h
---- libavcodec/avcodec.h	9 Dec 2005 16:08:18 -0000	1.430
-+++ libavcodec/avcodec.h	16 Dec 2005 11:18:15 -0000
+diff -ruN --exclude=CVS ffmpeg-cvs/libavcodec/avcodec.h ffmpeg-cvs-dirac/libavcodec/avcodec.h
+--- ffmpeg-cvs/libavcodec/avcodec.h	2005-11-30 01:40:50.000000000 +0000
++++ ffmpeg-cvs-dirac/libavcodec/avcodec.h	2005-12-01 11:56:28.000000000 +0000
 @@ -111,6 +111,7 @@
      CODEC_ID_WNV1,
      CODEC_ID_AASC,
@@ -212,7 +109,7 @@ diff -u -r1.430 avcodec.h
      CODEC_ID_FRAPS,
      CODEC_ID_TRUEMOTION2,
      CODEC_ID_BMP,
-@@ -1970,6 +1973,7 @@
+@@ -1969,6 +1972,7 @@
  extern AVCodec sonic_ls_encoder;
  extern AVCodec svq1_encoder;
  extern AVCodec x264_encoder;
@@ -220,7 +117,7 @@ diff -u -r1.430 avcodec.h
  
  extern AVCodec h263_decoder;
  extern AVCodec h261_decoder;
-@@ -2075,6 +2079,7 @@
+@@ -2073,6 +2077,7 @@
  extern AVCodec libgsm_encoder;
  extern AVCodec libgsm_decoder;
  extern AVCodec bmp_decoder;
@@ -228,70 +125,9 @@ diff -u -r1.430 avcodec.h
  
  /* pcm codecs */
  #define PCM_CODEC(id, name) \
-Index: libavformat/Makefile
-===================================================================
-RCS file: /cvsroot/ffmpeg/ffmpeg/libavformat/Makefile,v
-retrieving revision 1.103
-diff -u -r1.103 Makefile
---- libavformat/Makefile	10 Dec 2005 17:14:23 -0000	1.103
-+++ libavformat/Makefile	16 Dec 2005 11:18:16 -0000
-@@ -6,7 +6,7 @@
- 
- VPATH=$(SRC_PATH)/libavformat
- 
--CFLAGS=$(OPTFLAGS) -I.. -I$(SRC_PATH) -I$(SRC_PATH)/libavutil -I$(SRC_PATH)/libavcodec -DHAVE_AV_CONFIG_H -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE
-+CFLAGS=$(OPTFLAGS) -I.. -I$(SRC_PATH) -I$(SRC_PATH)/libavutil -I$(SRC_PATH)/libavcodec $(EXTRAINCS) -DHAVE_AV_CONFIG_H -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE
- 
- OBJS= utils.o cutils.o os_support.o allformats.o
- PPOBJS=
-@@ -36,6 +36,12 @@
- OBJS+= avio.o aviobuf.o file.o 
- OBJS+= framehook.o 
- 
-+ifeq ($(CONFIG_DIRAC),yes)
-+    OBJS+= drc.o
-+	EXTRALIBS+=$(DIRAC_LIB)
-+	CFLAGS+=$(DIRAC_INC)
-+endif
-+
- ifeq ($(CONFIG_VIDEO4LINUX),yes)
- OBJS+= grab.o
- endif
-Index: libavformat/allformats.c
-===================================================================
-RCS file: /cvsroot/ffmpeg/ffmpeg/libavformat/allformats.c,v
-retrieving revision 1.50
-diff -u -r1.50 allformats.c
---- libavformat/allformats.c	23 Sep 2005 00:25:41 -0000	1.50
-+++ libavformat/allformats.c	16 Dec 2005 11:18:16 -0000
-@@ -111,6 +111,10 @@
-     nsvdec_init();
-     daud_init();
- 
-+#ifdef CONFIG_DIRAC
-+    drc_init();
-+#endif
-+
- #ifdef CONFIG_MUXERS
-     /* image formats */
- #if 0
-Index: libavformat/avienc.c
-===================================================================
-RCS file: /cvsroot/ffmpeg/ffmpeg/libavformat/avienc.c,v
-retrieving revision 1.115
-diff -u -r1.115 avienc.c
---- libavformat/avienc.c	30 Nov 2005 10:50:13 -0000	1.115
-+++ libavformat/avienc.c	16 Dec 2005 11:18:18 -0000
-@@ -193,6 +193,7 @@
-     { CODEC_ID_FRAPS, MKTAG('F', 'P', 'S', '1') },
-     { CODEC_ID_THEORA, MKTAG('t', 'h', 'e', 'o') },
-     { CODEC_ID_TRUEMOTION2, MKTAG('T', 'M', '2', '0') },
-+    { CODEC_ID_DIRAC, MKTAG('d', 'r', 'a', 'c') },
-     { CODEC_ID_RAWVIDEO, 0 },
-     { 0, 0 },
- };
---- /dev/null	2005-12-09 12:34:30.989462208 +0200
-+++ libavcodec/dirac.c	2005-12-16 13:10:14.789099688 +0200
+diff -ruN --exclude=CVS ffmpeg-cvs/libavcodec/dirac.c ffmpeg-cvs-dirac/libavcodec/dirac.c
+--- ffmpeg-cvs/libavcodec/dirac.c	1970-01-01 01:00:00.000000000 +0100
++++ ffmpeg-cvs-dirac/libavcodec/dirac.c	2005-09-02 12:49:18.000000000 +0100
 @@ -0,0 +1,509 @@
 +/**
 + * @file dirac.c
@@ -802,8 +638,59 @@ diff -u -r1.115 avienc.c
 +
 +
 +
---- /dev/null	2005-12-09 12:34:30.989462208 +0200
-+++ libavformat/drc.c	2005-12-16 13:10:14.805097256 +0200
+diff -ruN --exclude=CVS ffmpeg-cvs/libavcodec/Makefile ffmpeg-cvs-dirac/libavcodec/Makefile
+--- ffmpeg-cvs/libavcodec/Makefile	2005-11-30 01:40:50.000000000 +0000
++++ ffmpeg-cvs-dirac/libavcodec/Makefile	2005-12-01 11:52:32.000000000 +0000
+@@ -7,7 +7,7 @@
+ VPATH=$(SRC_PATH)/libavcodec
+ 
+ # NOTE: -I.. is needed to include config.h
+-CFLAGS=$(OPTFLAGS) -DHAVE_AV_CONFIG_H -I.. -I$(SRC_PATH)/libavutil -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE $(AMR_CFLAGS)
++CFLAGS=$(OPTFLAGS) -DHAVE_AV_CONFIG_H -I.. -I$(SRC_PATH)/libavutil -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE $(AMR_CFLAGS) $(EXTRAINCS)
+ 
+ OBJS= bitstream.o utils.o mem.o allcodecs.o \
+       mpegvideo.o jrevdct.o jfdctfst.o jfdctint.o\
+@@ -301,6 +301,12 @@
+ endif
+ endif
+ 
++ifeq ($(CONFIG_DIRAC),yes)
++OBJS += dirac.o
++EXTRALIBS += $(DIRAC_LIB)
++CFLAGS += $(DIRAC_INC)
++endif
++
+ ifeq ($(CONFIG_LIBGSM),yes)
+ OBJS += libgsm.o
+ endif
+diff -ruN --exclude=CVS ffmpeg-cvs/libavformat/allformats.c ffmpeg-cvs-dirac/libavformat/allformats.c
+--- ffmpeg-cvs/libavformat/allformats.c	2005-09-23 01:25:41.000000000 +0100
++++ ffmpeg-cvs-dirac/libavformat/allformats.c	2005-11-15 11:40:08.000000000 +0000
+@@ -111,6 +111,10 @@
+     nsvdec_init();
+     daud_init();
+ 
++#ifdef CONFIG_DIRAC
++    drc_init();
++#endif
++
+ #ifdef CONFIG_MUXERS
+     /* image formats */
+ #if 0
+diff -ruN --exclude=CVS ffmpeg-cvs/libavformat/avienc.c ffmpeg-cvs-dirac/libavformat/avienc.c
+--- ffmpeg-cvs/libavformat/avienc.c	2005-11-30 10:50:13.000000000 +0000
++++ ffmpeg-cvs-dirac/libavformat/avienc.c	2005-12-01 11:52:33.000000000 +0000
+@@ -193,6 +193,7 @@
+     { CODEC_ID_FRAPS, MKTAG('F', 'P', 'S', '1') },
+     { CODEC_ID_THEORA, MKTAG('t', 'h', 'e', 'o') },
+     { CODEC_ID_TRUEMOTION2, MKTAG('T', 'M', '2', '0') },
++    { CODEC_ID_DIRAC, MKTAG('d', 'r', 'a', 'c') },
+     { CODEC_ID_RAWVIDEO, 0 },
+     { 0, 0 },
+ };
+diff -ruN --exclude=CVS ffmpeg-cvs/libavformat/drc.c ffmpeg-cvs-dirac/libavformat/drc.c
+--- ffmpeg-cvs/libavformat/drc.c	1970-01-01 01:00:00.000000000 +0100
++++ ffmpeg-cvs-dirac/libavformat/drc.c	2005-09-02 12:49:18.000000000 +0100
 @@ -0,0 +1,300 @@
 +/**
 + * @file drc.c
@@ -1105,3 +992,42 @@ diff -u -r1.115 avienc.c
 +    return 0 ;
 +}
 +
+diff -ruN --exclude=CVS ffmpeg-cvs/libavformat/Makefile ffmpeg-cvs-dirac/libavformat/Makefile
+--- ffmpeg-cvs/libavformat/Makefile	2005-11-07 01:32:29.000000000 +0000
++++ ffmpeg-cvs-dirac/libavformat/Makefile	2005-11-15 11:36:23.000000000 +0000
+@@ -6,7 +6,7 @@
+ 
+ VPATH=$(SRC_PATH)/libavformat
+ 
+-CFLAGS=$(OPTFLAGS) -I.. -I$(SRC_PATH) -I$(SRC_PATH)/libavutil -I$(SRC_PATH)/libavcodec -DHAVE_AV_CONFIG_H -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE
++CFLAGS=$(OPTFLAGS) -I.. -I$(SRC_PATH) -I$(SRC_PATH)/libavutil -I$(SRC_PATH)/libavcodec $(EXTRAINCS) -DHAVE_AV_CONFIG_H -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE
+ 
+ OBJS= utils.o cutils.o os_support.o allformats.o
+ PPOBJS=
+@@ -36,6 +36,12 @@
+ OBJS+= avio.o aviobuf.o file.o 
+ OBJS+= framehook.o 
+ 
++ifeq ($(CONFIG_DIRAC),yes)
++    OBJS+= drc.o
++	EXTRALIBS+=$(DIRAC_LIB)
++	CFLAGS+=$(DIRAC_INC)
++endif
++
+ ifeq ($(CONFIG_VIDEO4LINUX),yes)
+ OBJS+= grab.o
+ endif
+diff -ruN --exclude=CVS ffmpeg-cvs/Makefile ffmpeg-cvs-dirac/Makefile
+--- ffmpeg-cvs/Makefile	2005-10-18 21:11:41.000000000 +0100
++++ ffmpeg-cvs-dirac/Makefile	2005-11-15 11:36:51.000000000 +0000
+@@ -14,6 +14,10 @@
+ LDFLAGS+=-p
+ endif
+ 
++ifeq ($(CONFIG_DIRAC),yes)
++CFLAGS+=$(EXTRAINCS) 
++endif
++
+ MANPAGE=doc/ffmpeg.1
+ PROG=ffmpeg$(EXESUF)
+ PROGTEST=output_example$(EXESUF)
